### ISSUE TITLE
Happy shipped with MinGHC fails to find data files

### ISSUE THREAD

**Issue by ndmitchell** [fpco/minghc#24] opened 2015-01-19 21:04 UTC
Trying to install haskell-src-exts I ended up with:

    happy.exe: C:\Documents and Settings\IEUser\Application Data\cabal\i386-windows-
    ghc-7.8.3\happy-1.19.4/HappyTemplate-arrays-coerce: openFile: does not exist (No
     such file or directory)

I'd already installed haskell-src-exts, but this time I was doing it with cabal from the directory, rather than with `cabal install haskell-src-exts`, which might make a difference? Either way, something worth looking at, since we don't ship the happy data files.

**Comment by tejon** [comment] 2015-01-19 22:42
I ran into this too and it seems to be a problem with `happy` itself (also `alex`) since it persists after building from Hackage. The problem is the static reference to IEUser (and Win9x directory structure, though there are hidden symlinks that should allow for that in later Windows).

I personally fixed it by creating my own directory junctions to redirect the path `happy` and `alex` search so they find their stuff, but I don't think that's a good idea here, heh.

**Comment by ndmitchell** [comment] 2015-01-20 13:26
So the "right" thing to do is probably put the data files next to the binaries, and use getExecutablePath (in the Paths_happy.hs file) to find the nearby files. Might require rebuilding happy/alex though, but that's the only sane way to distribute binaries for them.

**Comment by tomberek** [comment] 2015-02-21 14:18
ran into same problem with CCA package

**Comment by ian-ross** [comment] 2015-02-24 17:17
I got around this by removing the versions of alex.exe and happy.exe in the MinGHC distribution then installing both Alex and Happy with Cabal.  Without the MinGHC versions, the Cabal-installed versions work fine.

And a quick fanboy moment: MinGHC is *great*.  I was dreading getting GHC working on Windows, but it's been almost completely painless!

**Comment by snoyberg** [comment] 2015-02-24 17:19
Thanks for the feedback!

@ndmitchell Should we just remove those executables for now, as they seem to be causing more problems than they're solving?

**Comment by ndmitchell** [comment] 2015-02-24 20:13
@snoyberg I might have a go at making sane Alex/Happy versions tomorrow and bundling them. If not, then yes, we should remove them.

**Comment by ndmitchell** [comment] 2015-02-25 17:11
I've put versions at http://hoogle.haskell.org/alex.zip and http://hoogle.haskell.org/happy.zip. Note that these will be deleted automatically in 3 hours, so @snoyberg please mirror them before then :). If you extract the contents of the zip into a directory, with the data files next to the executables, then they "just work".

Changes I made:

* Copy the data files into the same location as the exe.
* Replace `getDataDir` with `takeDirectory <$> getExecutablePath`.

Perhaps we could upstream some of that? Perhaps putting it all behind a flag? Ping @simonmar.

**Comment by snoyberg** [comment] 2015-02-25 18:22
Uploaded to:

* https://s3.amazonaws.com/download.fpcomplete.com/minghc/alex-2015-02-25.zip
* https://s3.amazonaws.com/download.fpcomplete.com/minghc/happy-2015-02-25.zip

**Comment by fegu** [comment] 2015-04-08 08:13
I second removing them altogether and perhaps replace with either docs or a post-install build. Caused me some trouble. Other than this, MinGHC looks very promising.

**Comment by snoyberg** [comment] 2015-04-08 08:20
@ndmitchell Did you switch the code to use the newly uploaded alex and happy, or is it still using the old one? If the old one, perhaps you can update the scripts and then I'll regenerate a new installer for testing?

**Comment by ndmitchell** [comment] 2015-04-08 10:00
I have not yet, but I'll try and do it tomorrow.

**Comment by simonmar** [comment] 2015-04-08 16:53
Cabal is supposed to do this, so you don't have to muck with `getExecutablePath` yourself.  See https://www.haskell.org/cabal/users-guide/installing-packages.html#prefix-independence

**Comment by ndmitchell** [comment] 2015-04-08 20:35
Thanks @simonmar, I wasn't aware of that feature, but I'll compile fresh binaries with those magic flags tomorrow and we'll incorporate those.

**Comment by ndmitchell** [comment] 2015-04-09 13:29
I've uploaded binaries the way @simonmar suggested at:

* http://community.haskell.org/~ndm/temp/happy-1.19.5.zip
* http://community.haskell.org/~ndm/temp/alex-3.1.4.zip

@snoyberg, can you please mirror them.

The recipe, in case anyone wants to repeat it, is:

    $ cabal install --bindir=$prefix --libdir=$prefix --datadir=$prefix --libexecdir=$prefix --prefix=c:\Neil\alex-3.1.4\bin
    $ cabal configure --bindir=$prefix --libdir=$prefix --datadir=$prefix --libexecdir=$prefix --prefix=c:\Neil\alex-3.1.4\bin
    $ cabal build
    $ copy dist\build\alex\alex.exe bin\alex.exe

Doesn't that look convoluted and nuts? Yes. But that's Cabal for you. Remember that `cabal install` silently downgrades to an older version of Cabal, so I install to get the data files, then `configure`/`build` on the new version of Cabal which supports prefix independence and copy just the binary over (because typing `install` again makes it rebuild with an older Cabal).

I'm unlikely to take a look at updating the installer today, and am away from my computer until Wednesday, so no rush on the uploading.

**Comment by rickdzekman** [comment] 2015-04-11 08:21
Just a quick note - I had the same problem.

When I deleted alex.exe and happy.exe from `C:\Program Files\MinGHC-7.8.4\bin` and used alex/happy from `cabal install alex happy` I was then able to install `haskell-src-exts` via `cabal intall` in bash.

**Comment by rpaladugu1** [comment] 2015-04-11 14:07
This problem still exists in 7.8.3 win32 bit install. It is still referring to nonexistent file location when alex or happy are used. Solution is to delete or rename them and reinstall.

**Comment by snoyberg** [comment] 2015-04-12 10:03
Uploaded to:

* https://s3.amazonaws.com/download.fpcomplete.com/minghc/alex-3.1.4.zip
* https://s3.amazonaws.com/download.fpcomplete.com/minghc/happy-1.19.5.zip

**Comment by ndmitchell** [comment] 2015-04-17 21:52
I've switched over to use the new zip files, and testing seems to show it working as expected. Please regenerate all the binaries when you have time - I'm not intending to tackle any other issues in the next few weeks and this is certainly our FAQ.

**Comment by snoyberg** [comment] 2015-04-18 18:45
Will do, most likely will have an upload available tomorrow.

**Comment by snoyberg** [comment] 2015-04-19 06:43
Here are two updated versions (just 32-bit for now, running the 64-bit ones and will upload later):

* https://s3.amazonaws.com/download.fpcomplete.com/minghc/minghc-7.10.1-i386-2015-04-19.exe
* https://s3.amazonaws.com/download.fpcomplete.com/minghc/minghc-7.8.4-i386-2015-04-19.exe

If someone can confirm that the problem is fixed, I'll update the README to point to these (or alternatively replace the original file names with these updates). I've tested myself, and it seems to be working.

**Comment by snoyberg** [comment] 2015-04-19 12:30
Another link:

* https://s3.amazonaws.com/download.fpcomplete.com/minghc/minghc-7.8.4-x86_64-2015-04-19.exe

**Comment by snoyberg** [comment] 2015-04-19 14:06
* https://s3.amazonaws.com/download.fpcomplete.com/minghc/minghc-7.10.1-x86_64-2015-04-19.exe

**Comment by ndmitchell** [comment] 2015-04-19 21:56
I just installed hlint (requires haskell-src-exts which uses happy) with the 32bit GHC 7.10.1 version, It went nicely. I think replacing the original file names is probably best - people can pick their GHC, but should be forced to take our latest package, since anyone needing an old one should report it to us.

**Comment by snoyberg** [comment] 2015-04-20 04:46
Alright, renames applied. That seems to resolve things, so closing.

**Closed by snoyberg** 2015-04-20 04:46 UTC

**Comment by gbaz** [comment] 2015-04-22 04:12
So, to confirm, we no longer need to ask that people install happy and alex after the install?

**Comment by snoyberg** [comment] 2015-04-22 04:13
That should be the case, correct. Thanks for the ping, I'll update the README here.
