### ISSUE TITLE
Build for GHC 7.8.4 (32-bit)

### ISSUE THREAD

**Issue by 3noch** [fpco/minghc#26] opened 2015-01-26 22:36 UTC
We have 7.8.4 for 64-bit, but not 32-bit

**Comment by ndmitchell** [comment] 2015-01-27 09:51
That's because GHC HQ haven't provided a 32 bit binary for GHC, which seems a bit of an omission. Pinging @hvr and @thoughtpolice.

**Comment by hvr** [comment] 2015-01-27 12:45
@ndmitchell Afaik, the problem is that @thoughtpolice isn't able to get his 32bit Win32 environment working again... maybe if somebody can help him out with that it would accelerate matters...

**Comment by ndmitchell** [comment] 2015-01-27 12:51
Is there anything in particular @thoughtpolice was running into? Happy to help if I can. Ideally I'd have hoped that the Windows build was done in a VM on Linux, which is how @snoyberg does it (but I realize all these things take time).

**Comment by thoughtpolice** [comment] 2015-01-28 02:31
No, it was mostly just issues with Rackspace I think and the Sourceforge mirrors for MSYS2 packages. I'm attempting to rebuild a new 32bit VM locally...

**Comment by hvr** [comment] 2015-03-28 09:05
Btw, http://downloads.haskell.org/~ghc/7.8.4/ghc-7.8.4-i386-unknown-mingw32.tar.xz

**Comment by snoyberg** [comment] 2015-03-29 06:07
Thanks @hvr, new version at https://s3.amazonaws.com/download.fpcomplete.com/minghc/minghc-7.8.4-i386.exe . If someone can test and let me know if it works, I'll update the README.

You're right, there's no reason not to have a 64-bit 7.10, generating it now.

**Comment by snoyberg** [comment] 2015-03-29 07:15
GHC 7.10.1 64-bit now available for testing: https://s3.amazonaws.com/download.fpcomplete.com/minghc/minghc-7.10.1-x86_64.exe

**Comment by 3noch** [comment] 2015-03-30 23:56
@snoyberg That latest 64-bit build doesn't seem to be signed? Windows warned me before letting me run it.

**Comment by 3noch** [comment] 2015-03-31 00:05
@snoyberg The 32-bit version is working for me as far as I can tell.

**Comment by snoyberg** [comment] 2015-03-31 05:36
I didn't do any signing for either executable, and am frankly completely ignorant of signing procedures for windows. If you can provide more information in what needs to be done, perhaps we can add signing to the build process.

**Comment by 3noch** [comment] 2015-03-31 17:11
@snoyberg 64-bit installer works as well, from my minor usage. I am not sure that signing was the issue. I was only surprised that the 32-bit installer did not elicit a warning but the 64-bit installer did. It's not a big problem for now since you just tell Windows to "Run anyway".

**Comment by snoyberg** [comment] 2015-03-31 17:31
This build is now provided, closing.

**Closed by snoyberg** 2015-03-31 17:31 UTC

**Comment by hgolden** [comment] 2015-04-22 22:35
According to @snoyberg there is a 32-bit version of 7.8.4, but it isn't shown on the webpage (https://github.com/fpco/minghc) under "Using the Installer". Please add a link so others can find it. Thanks.

**Comment by snoyberg** [comment] 2015-04-23 03:18
Oops, that was a mistake. Updated now.
