### ISSUE TITLE
can not install split due file missing time and failed to load interface after first time install minghc 7.10.2.-i386

### ISSUE THREAD

**Issue by LovelyYanki** [fpco/minghc#96] opened 2015-12-04 05:51 UTC
WARNING: cache is out of date: C:/Users/mmartin/AppData/Local/Programs/minghc-7.
10.2-i386/ghc-7.10.2\lib\package.conf.d\package.cache
ghc will see an old view of this package db. Use 'ghc-pkg recache' to fix.
There are problems in package xhtml-3000.2.1:
  Warning: library-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i
386\ghc-7.10.2\lib\xhtml_FxPylgBilld3tRCpn3X21N doesn't exist or isn't a directo
ry
  import-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i386\ghc-7.
10.2\lib\xhtml_FxPylgBilld3tRCpn3X21N doesn't exist or isn't a directory
  cannot find any of ["Text\\XHtml.hi","Text\\XHtml.p_hi","Text\\XHtml.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Frameset.hi","Text\\XHtml\\Frameset.p_hi","T
ext\\XHtml\\Frameset.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Strict.hi","Text\\XHtml\\Strict.p_hi","Text\
\XHtml\\Strict.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Transitional.hi","Text\\XHtml\\Transitional.
p_hi","Text\\XHtml\\Transitional.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Debug.hi","Text\\XHtml\\Debug.p_hi","Text\\X
Html\\Debug.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Table.hi","Text\\XHtml\\Table.p_hi","Text\\X
Html\\Table.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Strict\\Attributes.hi","Text\\XHtml\\Strict\
\Attributes.p_hi","Text\\XHtml\\Strict\\Attributes.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Strict\\Elements.hi","Text\\XHtml\\Strict\\E
lements.p_hi","Text\\XHtml\\Strict\\Elements.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Frameset\\Attributes.hi","Text\\XHtml\\Frame
set\\Attributes.p_hi","Text\\XHtml\\Frameset\\Attributes.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Frameset\\Elements.hi","Text\\XHtml\\Framese
t\\Elements.p_hi","Text\\XHtml\\Frameset\\Elements.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Transitional\\Attributes.hi","Text\\XHtml\\T
ransitional\\Attributes.p_hi","Text\\XHtml\\Transitional\\Attributes.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Transitional\\Elements.hi","Text\\XHtml\\Tra
nsitional\\Elements.p_hi","Text\\XHtml\\Transitional\\Elements.dyn_hi"]
  cannot find any of ["Text\\XHtml\\BlockTable.hi","Text\\XHtml\\BlockTable.p_hi
","Text\\XHtml\\BlockTable.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Extras.hi","Text\\XHtml\\Extras.p_hi","Text\
\XHtml\\Extras.dyn_hi"]
  cannot find any of ["Text\\XHtml\\Internals.hi","Text\\XHtml\\Internals.p_hi",
"Text\\XHtml\\Internals.dyn_hi"]
  cannot find any of ["libHSxhtml-3000.2.1-FxPylgBilld3tRCpn3X21N.a","libHSxhtml
-3000.2.1-FxPylgBilld3tRCpn3X21N.p_a","libHSxhtml-3000.2.1-FxPylgBilld3tRCpn3X21
N-ghc7.10.2.so","libHSxhtml-3000.2.1-FxPylgBilld3tRCpn3X21N-ghc7.10.2.dylib","HS
xhtml-3000.2.1-FxPylgBilld3tRCpn3X21N-ghc7.10.2.dll"] on library path
There are problems in package Win32-2.3.1.0:
  Warning: library-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i
386\ghc-7.10.2\lib\Win32_JH0ECVJdFmmG0JOvttvGqi doesn't exist or isn't a directo
ry
  Warning: include-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i
386\ghc-7.10.2\lib\Win32_JH0ECVJdFmmG0JOvttvGqi\include doesn't exist or isn't a
 directory
  import-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i386\ghc-7.
10.2\lib\Win32_JH0ECVJdFmmG0JOvttvGqi doesn't exist or isn't a directory
  cannot find any of ["Graphics\\Win32\\GDI.hi","Graphics\\Win32\\GDI.p_hi","Gra
phics\\Win32\\GDI.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Bitmap.hi","Graphics\\Win32\\GDI\\B
itmap.p_hi","Graphics\\Win32\\GDI\\Bitmap.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Brush.hi","Graphics\\Win32\\GDI\\Br
ush.p_hi","Graphics\\Win32\\GDI\\Brush.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Clip.hi","Graphics\\Win32\\GDI\\Cli
p.p_hi","Graphics\\Win32\\GDI\\Clip.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Font.hi","Graphics\\Win32\\GDI\\Fon
t.p_hi","Graphics\\Win32\\GDI\\Font.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Graphics2D.hi","Graphics\\Win32\\GD
I\\Graphics2D.p_hi","Graphics\\Win32\\GDI\\Graphics2D.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\HDC.hi","Graphics\\Win32\\GDI\\HDC.
p_hi","Graphics\\Win32\\GDI\\HDC.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Palette.hi","Graphics\\Win32\\GDI\\
Palette.p_hi","Graphics\\Win32\\GDI\\Palette.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Path.hi","Graphics\\Win32\\GDI\\Pat
h.p_hi","Graphics\\Win32\\GDI\\Path.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Pen.hi","Graphics\\Win32\\GDI\\Pen.
p_hi","Graphics\\Win32\\GDI\\Pen.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Region.hi","Graphics\\Win32\\GDI\\R
egion.p_hi","Graphics\\Win32\\GDI\\Region.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\GDI\\Types.hi","Graphics\\Win32\\GDI\\Ty
pes.p_hi","Graphics\\Win32\\GDI\\Types.dyn_hi"]
  cannot find any of ["Graphics\\Win32.hi","Graphics\\Win32.p_hi","Graphics\\Win
32.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\Control.hi","Graphics\\Win32\\Control.p_
hi","Graphics\\Win32\\Control.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\Dialogue.hi","Graphics\\Win32\\Dialogue.
p_hi","Graphics\\Win32\\Dialogue.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\Icon.hi","Graphics\\Win32\\Icon.p_hi","G
raphics\\Win32\\Icon.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\Key.hi","Graphics\\Win32\\Key.p_hi","Gra
phics\\Win32\\Key.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\Menu.hi","Graphics\\Win32\\Menu.p_hi","G
raphics\\Win32\\Menu.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\Message.hi","Graphics\\Win32\\Message.p_
hi","Graphics\\Win32\\Message.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\Misc.hi","Graphics\\Win32\\Misc.p_hi","G
raphics\\Win32\\Misc.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\Resource.hi","Graphics\\Win32\\Resource.
p_hi","Graphics\\Win32\\Resource.dyn_hi"]
  cannot find any of ["Graphics\\Win32\\Window.hi","Graphics\\Win32\\Window.p_hi
","Graphics\\Win32\\Window.dyn_hi"]
  cannot find any of ["System\\Win32.hi","System\\Win32.p_hi","System\\Win32.dyn
_hi"]
  cannot find any of ["System\\Win32\\DebugApi.hi","System\\Win32\\DebugApi.p_hi
","System\\Win32\\DebugApi.dyn_hi"]
  cannot find any of ["System\\Win32\\DLL.hi","System\\Win32\\DLL.p_hi","System\
\Win32\\DLL.dyn_hi"]
  cannot find any of ["System\\Win32\\File.hi","System\\Win32\\File.p_hi","Syste
m\\Win32\\File.dyn_hi"]
  cannot find any of ["System\\Win32\\FileMapping.hi","System\\Win32\\FileMappin
g.p_hi","System\\Win32\\FileMapping.dyn_hi"]
  cannot find any of ["System\\Win32\\Info.hi","System\\Win32\\Info.p_hi","Syste
m\\Win32\\Info.dyn_hi"]
  cannot find any of ["System\\Win32\\Mem.hi","System\\Win32\\Mem.p_hi","System\
\Win32\\Mem.dyn_hi"]
  cannot find any of ["System\\Win32\\NLS.hi","System\\Win32\\NLS.p_hi","System\
\Win32\\NLS.dyn_hi"]
  cannot find any of ["System\\Win32\\Process.hi","System\\Win32\\Process.p_hi",
"System\\Win32\\Process.dyn_hi"]
  cannot find any of ["System\\Win32\\Registry.hi","System\\Win32\\Registry.p_hi
","System\\Win32\\Registry.dyn_hi"]
  cannot find any of ["System\\Win32\\SimpleMAPI.hi","System\\Win32\\SimpleMAPI.
p_hi","System\\Win32\\SimpleMAPI.dyn_hi"]
  cannot find any of ["System\\Win32\\Time.hi","System\\Win32\\Time.p_hi","Syste
m\\Win32\\Time.dyn_hi"]
  cannot find any of ["System\\Win32\\Console.hi","System\\Win32\\Console.p_hi",
"System\\Win32\\Console.dyn_hi"]
  cannot find any of ["System\\Win32\\Security.hi","System\\Win32\\Security.p_hi
","System\\Win32\\Security.dyn_hi"]
  cannot find any of ["System\\Win32\\Types.hi","System\\Win32\\Types.p_hi","Sys
tem\\Win32\\Types.dyn_hi"]
  cannot find any of ["System\\Win32\\Shell.hi","System\\Win32\\Shell.p_hi","Sys
tem\\Win32\\Shell.dyn_hi"]
  cannot find any of ["libHSWin32-2.3.1.0-JH0ECVJdFmmG0JOvttvGqi.a","libHSWin32-
2.3.1.0-JH0ECVJdFmmG0JOvttvGqi.p_a","libHSWin32-2.3.1.0-JH0ECVJdFmmG0JOvttvGqi-g
hc7.10.2.so","libHSWin32-2.3.1.0-JH0ECVJdFmmG0JOvttvGqi-ghc7.10.2.dylib","HSWin3
2-2.3.1.0-JH0ECVJdFmmG0JOvttvGqi-ghc7.10.2.dll"] on library path
There are problems in package transformers-0.4.2.0:
  Warning: library-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i
386\ghc-7.10.2\lib\trans_3eG64VdP2vzGjP6wJiCp5X doesn't exist or isn't a directo
ry
  import-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i386\ghc-7.
10.2\lib\trans_3eG64VdP2vzGjP6wJiCp5X doesn't exist or isn't a directory
  cannot find any of ["Control\\Applicative\\Backwards.hi","Control\\Applicative
\\Backwards.p_hi","Control\\Applicative\\Backwards.dyn_hi"]
  cannot find any of ["Control\\Applicative\\Lift.hi","Control\\Applicative\\Lif
t.p_hi","Control\\Applicative\\Lift.dyn_hi"]
  cannot find any of ["Control\\Monad\\IO\\Class.hi","Control\\Monad\\IO\\Class.
p_hi","Control\\Monad\\IO\\Class.dyn_hi"]
  cannot find any of ["Control\\Monad\\Signatures.hi","Control\\Monad\\Signature
s.p_hi","Control\\Monad\\Signatures.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Class.hi","Control\\Monad\\Trans\\
Class.p_hi","Control\\Monad\\Trans\\Class.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Cont.hi","Control\\Monad\\Trans\\C
ont.p_hi","Control\\Monad\\Trans\\Cont.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Except.hi","Control\\Monad\\Trans\
\Except.p_hi","Control\\Monad\\Trans\\Except.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Error.hi","Control\\Monad\\Trans\\
Error.p_hi","Control\\Monad\\Trans\\Error.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Identity.hi","Control\\Monad\\Tran
s\\Identity.p_hi","Control\\Monad\\Trans\\Identity.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\List.hi","Control\\Monad\\Trans\\L
ist.p_hi","Control\\Monad\\Trans\\List.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Maybe.hi","Control\\Monad\\Trans\\
Maybe.p_hi","Control\\Monad\\Trans\\Maybe.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Reader.hi","Control\\Monad\\Trans\
\Reader.p_hi","Control\\Monad\\Trans\\Reader.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\RWS.hi","Control\\Monad\\Trans\\RW
S.p_hi","Control\\Monad\\Trans\\RWS.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\RWS\\Lazy.hi","Control\\Monad\\Tra
ns\\RWS\\Lazy.p_hi","Control\\Monad\\Trans\\RWS\\Lazy.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\RWS\\Strict.hi","Control\\Monad\\T
rans\\RWS\\Strict.p_hi","Control\\Monad\\Trans\\RWS\\Strict.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\State.hi","Control\\Monad\\Trans\\
State.p_hi","Control\\Monad\\Trans\\State.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\State\\Lazy.hi","Control\\Monad\\T
rans\\State\\Lazy.p_hi","Control\\Monad\\Trans\\State\\Lazy.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\State\\Strict.hi","Control\\Monad\
\Trans\\State\\Strict.p_hi","Control\\Monad\\Trans\\State\\Strict.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Writer.hi","Control\\Monad\\Trans\
\Writer.p_hi","Control\\Monad\\Trans\\Writer.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Writer\\Lazy.hi","Control\\Monad\\
Trans\\Writer\\Lazy.p_hi","Control\\Monad\\Trans\\Writer\\Lazy.dyn_hi"]
  cannot find any of ["Control\\Monad\\Trans\\Writer\\Strict.hi","Control\\Monad
\\Trans\\Writer\\Strict.p_hi","Control\\Monad\\Trans\\Writer\\Strict.dyn_hi"]
  cannot find any of ["Data\\Functor\\Classes.hi","Data\\Functor\\Classes.p_hi",
"Data\\Functor\\Classes.dyn_hi"]
  cannot find any of ["Data\\Functor\\Compose.hi","Data\\Functor\\Compose.p_hi",
"Data\\Functor\\Compose.dyn_hi"]
  cannot find any of ["Data\\Functor\\Constant.hi","Data\\Functor\\Constant.p_hi
","Data\\Functor\\Constant.dyn_hi"]
  cannot find any of ["Data\\Functor\\Product.hi","Data\\Functor\\Product.p_hi",
"Data\\Functor\\Product.dyn_hi"]
  cannot find any of ["Data\\Functor\\Reverse.hi","Data\\Functor\\Reverse.p_hi",
"Data\\Functor\\Reverse.dyn_hi"]
  cannot find any of ["Data\\Functor\\Sum.hi","Data\\Functor\\Sum.p_hi","Data\\F
unctor\\Sum.dyn_hi"]
  cannot find any of ["libHStransformers-0.4.2.0-3eG64VdP2vzGjP6wJiCp5X.a","libH
Stransformers-0.4.2.0-3eG64VdP2vzGjP6wJiCp5X.p_a","libHStransformers-0.4.2.0-3eG
64VdP2vzGjP6wJiCp5X-ghc7.10.2.so","libHStransformers-0.4.2.0-3eG64VdP2vzGjP6wJiC
p5X-ghc7.10.2.dylib","HStransformers-0.4.2.0-3eG64VdP2vzGjP6wJiCp5X-ghc7.10.2.dl
l"] on library path
There are problems in package time-1.5.0.1:
  Warning: library-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i
386\ghc-7.10.2\lib\time_ECG3PhVYxEUEM046TXoOWk doesn't exist or isn't a director
y
  Warning: include-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i
386\ghc-7.10.2\lib\time_ECG3PhVYxEUEM046TXoOWk\include doesn't exist or isn't a
directory
  import-dirs: C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i386\ghc-7.
10.2\lib\time_ECG3PhVYxEUEM046TXoOWk doesn't exist or isn't a directory
  cannot find any of ["Data\\Time\\Calendar.hi","Data\\Time\\Calendar.p_hi","Dat
a\\Time\\Calendar.dyn_hi"]
  cannot find any of ["Data\\Time\\Calendar\\MonthDay.hi","Data\\Time\\Calendar\
\MonthDay.p_hi","Data\\Time\\Calendar\\MonthDay.dyn_hi"]
  cannot find any of ["Data\\Time\\Calendar\\OrdinalDate.hi","Data\\Time\\Calend
ar\\OrdinalDate.p_hi","Data\\Time\\Calendar\\OrdinalDate.dyn_hi"]
  cannot find any of ["Data\\Time\\Calendar\\WeekDate.hi","Data\\Time\\Calendar\
\WeekDate.p_hi","Data\\Time\\Calendar\\WeekDate.dyn_hi"]
  cannot find any of ["Data\\Time\\Calendar\\Julian.hi","Data\\Time\\Calendar\\J
ulian.p_hi","Data\\Time\\Calendar\\Julian.dyn_hi"]
  cannot find any of ["Data\\Time\\Calendar\\Easter.hi","Data\\Time\\Calendar\\E
aster.p_hi","Data\\Time\\Calendar\\Easter.dyn_hi"]
  cannot find any of ["Data\\Time\\Clock.hi","Data\\Time\\Clock.p_hi","Data\\Tim
e\\Clock.dyn_hi"]
  cannot find any of ["Data\\Time\\Clock\\POSIX.hi","Data\\Time\\Clock\\POSIX.p_
hi","Data\\Time\\Clock\\POSIX.dyn_hi"]
  cannot find any of ["Data\\Time\\Clock\\TAI.hi","Data\\Time\\Clock\\TAI.p_hi",
"Data\\Time\\Clock\\TAI.dyn_hi"]
  cannot find any of ["Data\\Time\\LocalTime.hi","Data\\Time\\LocalTime.p_hi","D
ata\\Time\\LocalTime.dyn_hi"]
  cannot find any of ["Data\\Time\\Format.hi","Data\\Time\\Format.p_hi","Data\\T
ime\\Format.dyn_hi"]
  cannot find any of ["Data\\Time.hi","Data\\Time.p_hi","Data\\Time.dyn_hi"]
  cannot find any of ["Data\\Time\\Calendar\\Private.hi","Data\\Time\\Calendar\\
Private.p_hi","Data\\Time\\Calendar\\Private.dyn_hi"]
  cannot find any of ["Data\\Time\\Calendar\\Days.hi","Data\\Time\\Calendar\\Day
s.p_hi","Data\\Time\\Calendar\\Days.dyn_hi"]
  cannot find any of ["Data\\Time\\Calendar\\Gregorian.hi","Data\\Time\\Calendar
\\Gregorian.p_hi","Data\\Time\\Calendar\\Gregorian.dyn_hi"]
  cannot find any of ["Data\\Time\\Calendar\\JulianYearDay.hi","Data\\Time\\Cale
ndar\\JulianYearDay.p_hi","Data\\Time\\Calendar\\JulianYearDay.dyn_hi"]
  cannot find any of ["Data\\Time\\Clock\\Scale.hi","Data\\Time\\Clock\\Scale.p_
hi","Data\\Time\\Clock\\Scale.dyn_hi"]
  cannot find any of ["Data\\Time\\Clock\\UTC.hi","Data\\Time\\Clock\\UTC.p_hi",
"Data\\Time\\Clock\\UTC.dyn_hi"]
  cannot find any of ["Data\\Time\\Clock\\CTimeval.hi","Data\\Time\\Clock\\CTime
val.p_hi","Data\\Time\\Clock\\CTimeval.dyn_hi"]
  cannot find any of ["Data\\Time\\Clock\\UTCDiff.hi","Data\\Time\\Clock\\UTCDif
f.p_hi","Data\\Time\\Clock\\UTCDiff.dyn_hi"]
  cannot find any of ["Data\\Time\\LocalTime\\TimeZone.hi","Data\\Time\\LocalTim
e\\TimeZone.p_hi","Data\\Time\\LocalTime\\TimeZone.dyn_hi"]
  cannot find any of ["Data\\Time\\LocalTime\\TimeOfDay.hi","Data\\Time\\LocalTi
me\\TimeOfDay.p_hi","Data\\Time\\LocalTime\\TimeOfDay.dyn_hi"]
  cannot find any of ["Data\\Time\\LocalTime\\LocalTime.hi","Data\\Time\\LocalTi
me\\LocalTime.p_hi","Data\\Time\\LocalTime\\LocalTime.dyn_hi"]
  cannot find any of ["Data\\Time\\Format\\Parse.hi","Data\\Time\\Format\\Parse.
p_hi","Data\\Time\\Format\\Parse.dyn_hi"]
  cannot find any of ["Data\\Time\\Format\\Locale.hi","Data\\Time\\Format\\Local
e.p_hi","Data\\Time\\Format\\Locale.dyn_hi"]
  cannot find any of ["libHStime-1.5.0.1-ECG3PhVYxEUEM046TXoOWk.a","libHStime-1.
5.0.1-ECG3PhVYxEUEM046TXoOWk.p_a","libHStime-1.5.0.1-ECG3PhVYxEUEM046TXoOWk-ghc7
.10.2.so","libHStime-1.5.0.1-ECG3PhVYxEUEM046TXoOWk-ghc7.10.2.dylib","HStime-1.5
.0.1-ECG3PhVYxEUEM046TXoOWk-ghc7.10.2.dll"] on library path

The following packages are broken, either because they have a problem
listed above, or because they depend on a broken package.
xhtml-3000.2.1
Win32-2.3.1.0
transformers-0.4.2.0
time-1.5.0.1
process-1.2.3.0
hpc-0.6.0.2
haskeline-0.7.2.1
ghc-7.10.2
directory-1.2.2.0
Cabal-1.22.4.0
bin-package-db-0.0.0.0

C:\Users\tester>cabal install split > check2.txt
cabal: Error: some packages failed to install:
split-0.2.2 failed during the configure step. The exception was:
user error
('C:\Users\mmartin\AppData\Local\Programs\minghc-7.10.2-i386\ghc-7.10.2\bin\ghc.
exe'
exited with an error:
Failed to load interface for `Data.Time.Calendar.Gregorian'
There are files missing in the `time-1.5.0.1' package,
try running 'ghc-pkg check'.
Use -v to see a list of the files searched for.
)

**Comment by ndmitchell** [comment] 2015-12-04 10:13
I would strongly suggest trying out https://github.com/commercialhaskell/stack/ instead. None of the MinGHC developers still use this, we've all moved off to Stack.

It seems like you have got your package database into an inconsistent state, so uninstall/reinstall is the best approach if you do want to stick with MinGHC.

**Comment by 3noch** [comment] 2015-12-04 13:51
It's true.

Perhaps this should be deprecated officially?

**Comment by LovelyYanki** [comment] 2015-12-05 03:52
i am still using split in ubuntu 12 and works well. i think that split is not deprecated,
you mean minghc deprecated, so that i have to change to use stack ?

**Comment by LovelyYanki** [comment] 2015-12-05 03:54
my intel compute stick only left less than 1GB hard disk, so i choose minghc, thank you for your advice, i will change to use stack.

**Comment by ndmitchell** [comment] 2015-12-05 20:43
At the moment, `stack setup` then `stack exec -- cabal install hlint` is probably a much nicer experience than MinGHC, even if you don't want to "use stack", so yes, I'd be tempted to officially deprecate it (although not exactly sure what the looks like compared to the current front page, which is a reasonably forceful shove in the direction of Stack). Perhaps explicitly disclaim support and future enhancements? And go through the issue tracker closing them as won't fix, use stack (which I think probably reflects reality)? I'd be happy to write a blog post, summarising what we achieved, and announcing our joyous fade into oblivion. @3noch and @snoyberg, does that sound like a plan?

@LovelyYanki whether 1Gb is enough for Haskell is debatable - my MinGHC 7.10.2 install 32bit (which is about as small as you are going to get) takes 1.2Gb. Haskell is not known for its small binaries.

**Comment by 3noch** [comment] 2015-12-05 20:56
@ndmitchell I switched jobs and now use Haskell on a Mac (not for work, though). For my part, I won't be contributing anything more to MinGHC, not to mention stack is far superior on Windows anyway.

**Comment by 3noch** [comment] 2015-12-05 21:00
For the record, I normally just run `stack install hlint`.

**Comment by ndmitchell** [comment] 2015-12-05 21:01
Indeed, I'm merely saying that even if you don't want to use the `stack` approach to sandboxes/stackage etc, you can still use `cabal` after `stack setup`, and you'll probably get a reasonable MinGHC-like experience. Of course, I'd encourage people to use the full stack tool as intended.

**Comment by 3noch** [comment] 2015-12-05 21:01
:+1:

**Comment by snoyberg** [comment] 2015-12-06 07:52
@ndmitchell You have my full support on that :)

**Comment by ndmitchell** [comment] 2015-12-09 20:33
Done, I'm just going through closing the tickets, including this one! We now advise people use [Stack](https://github.com/commercialhaskell/stack) instead, MinGHC is no longer supported.

**Closed by ndmitchell** 2015-12-09 20:33 UTC
