### ISSUE TITLE
network-2.6.0.2 on MinGHC 7.10.1 and Cygwin

### ISSUE THREAD

**Issue by guiraldelli** [fpco/minghc#33] opened 2015-03-30 13:52 UTC
I have a plain new installation of MinGHC 7.10.1 and I have tried to install the dependencies of my cabal sandbox when, suddenly, I get the following message:

```
$ cabal repl
Preprocessing executable 'myproject' for myproject-0.1.0.0...
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
ghc.exe: unable to load package `network-2.6.0.2'
ghc.exe: C:\directory-of-project\.cabal-sandbox\i386-windows-ghc-7.10.1\netwo_7d76Yx3J1NVCM4gO06psKu\HSnetwork-2.6.0.2-7d76Yx3J1NVCM4gO06psKu.o: unknown symbol `_shutdownWinSock'
```

The same problem happened when I have installed the MinGHC 7.8.3.

**Comment by snoyberg** [comment] 2015-03-30 18:55
I just tested, and I was unable to reproduce. My steps were:

* Create a new project which uses the network package
* `cabal sandbox init`
* `cabal install`, which forced network to be installed
* `cabal repl`
* `import Network`, just for good measure

Can you confirm that these steps reproduce the issue on your machine?

**Comment by ndmitchell** [comment] 2015-03-30 19:34
@snoyberg try `Network.withSocketsDo $ return ()` - sometimes linking is deferred until the first function is called.

**Comment by snoyberg** [comment] 2015-03-30 19:44
Worked fine, no issue.

**Comment by guiraldelli** [comment] 2015-03-31 07:34
Gentlemen, I have tried the steps you've requested. What I found out is: `network` package and Cygwin doesn't seem to like each other. But everything goes fine with the ugly Command Prompt.

Could you guys confirm it? And how is it relevant for the MinGHC project?

Thank you for your replies and nice project. :)

**Comment by snoyberg** [comment] 2015-03-31 08:17
That sounds right. Would you be able to send a PR to update the README with
this information?

**Comment by snoyberg** [comment] 2015-03-31 17:22
Given the updated content in the README, closing.

**Closed by snoyberg** 2015-03-31 17:22 UTC
